FROM python:3.11-slim

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt ./
COPY requirements.dev.txt ./
RUN pip install --no-cache-dir -r requirements.dev.txt

COPY . .

RUN chmod +x scripts/start.sh

ENTRYPOINT ["sh", "scripts/start.sh"]
CMD ["--reload"]
