version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ayre_fren_db
      POSTGRES_USER: ayre_user
      POSTGRES_PASSWORD: ayre_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://ayre_user:ayre_password@db:5432/ayre_fren_db
      TEST_DATABASE_URL: postgresql+asyncpg://ayre_user:ayre_password@db:5432/ayre_fren_test_db
      DEV_SEED: "1"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
