"""Update invoice_types name field

Revision ID: 603cc80f101c
Revises: 3e316f7e581f
Create Date: 2025-07-07 18:14:21.685646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603cc80f101c'
down_revision: Union[str, Sequence[str], None] = '3e316f7e581f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_types', 'name',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_types', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
