"""correction work order part

Revision ID: 8969ddfc864e
Revises: 2f28cbc4e7ad
Create Date: 2025-07-02 23:17:36.460384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8969ddfc864e'
down_revision: Union[str, Sequence[str], None] = '2f28cbc4e7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_parts', sa.Column('increment_per_unit', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_parts', 'increment_per_unit')
    # ### end Alembic commands ###
