"""migraciones

Revision ID: a7ddd162d893
Revises: 2f7dbcfd15e0
Create Date: 2025-07-18 19:26:09.115532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ddd162d893'
down_revision: Union[str, Sequence[str], None] = '2f7dbcfd15e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_types', sa.Column('surcharge', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('work_order_tasks', sa.Column('external', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_tasks', 'external')
    op.drop_column('invoice_types', 'surcharge')
    # ### end Alembic commands ###
