"""corrections

Revision ID: bf52b619babd
Revises: e064e72c3e72
Create Date: 2025-07-07 18:12:05.341618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf52b619babd'
down_revision: Union[str, Sequence[str], None] = 'e064e72c3e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_types', sa.Column('name', sa.String(length=2), nullable=True))
    op.drop_constraint(op.f('invoice_types_code_key'), 'invoice_types', type_='unique')
    op.create_unique_constraint(None, 'invoice_types', ['name'])
    op.drop_column('invoice_types', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_types', sa.Column('code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice_types', type_='unique')
    op.create_unique_constraint(op.f('invoice_types_code_key'), 'invoice_types', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('invoice_types', 'name')
    # ### end Alembic commands ###
