"""corrections

Revision ID: e064e72c3e72
Revises: 319d8bbaa5f9
Create Date: 2025-07-07 18:10:44.916694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e064e72c3e72'
down_revision: Union[str, Sequence[str], None] = '319d8bbaa5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_checks', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bank_checks', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_checks', type_='foreignkey')
    op.drop_column('bank_checks', 'payment_id')
    # ### end Alembic commands ###
