"""migraciones

Revision ID: f1599be82b2a
Revises: 50a1abe26e91
Create Date: 2025-07-23 19:14:06.299884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1599be82b2a'
down_revision: Union[str, Sequence[str], None] = '50a1abe26e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_parts', sa.Column('name', sa.Text(), nullable=True))
    op.drop_constraint(op.f('work_order_parts_part_id_fkey'), 'work_order_parts', type_='foreignkey')
    op.drop_column('work_order_parts', 'part_id')
    op.add_column('work_orders', sa.Column('fast_phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'fast_phone')
    op.add_column('work_order_parts', sa.Column('part_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('work_order_parts_part_id_fkey'), 'work_order_parts', 'parts', ['part_id'], ['id'])
    op.drop_column('work_order_parts', 'name')
    # ### end Alembic commands ###
